introspection: file:///tmp/schema.graphql

servers:
  - url: https://demo.nearbycomputing.com
    description: Demo

info:
  title: NearbyComputing API
  description: Documentation for GraphQL API Gateway

domains:
  - name: Charts
    description: View information about one or more Block Charts
    usecases:
      - name: Block chart
        description: Fetch a chart by name and version
        query: query.blockChart
      - name: Block charts
        description: Fetch the latest versions of all charts in the marketplace
        query: query.blockCharts
      - name: Publish Block Chart
        description: Publish a new Block Chart based on an existing template
        query: mutation.publishBlockChart
      - name: Delete Block Chart
        description: Delete an existing Block Chart based on an existing template
        query: mutation.deleteBlockChart
      - name: Provision Chart
        description: Fetch the baremetal / software values of a Provisioning Chart
        query: query.provisionChart
      - name: Provision Charts
        description: Fetch a list of all versions of all Provision Charts
        query: query.provisionCharts
      - name: Cloud Resource Chart
        description: Fetch the default config of a Cloud Resource Chart
        query: query.cloudResourceChart
      - name: Cloud Resource Charts
        description: Fetch a list of the latest versions of all Cloud Resource Charts
        query: query.cloudResourceCharts
      - name: Publisher Template
        description: Fetch a publisher template by name and version
        query: query.templateChart
      - name: Publisher Template
        description: Fetch the latest versions of all Publisher Templates
        query: query.templateCharts

  - name: Connections
    description: View connections from a device or service
    usecases:
      - name: Fetch Connections
        description: List all connections from a given service or device
        query: query.connections

  - name: Crossplane Provisions
    description: Create and update Cloud Resource provisions
    usecases:
      - name: Cloud Resource Provision
        description: Provision a Cloud Resource
        query: mutation.cloudResource
      - name: Update Cloud Resource
        description: update a provisioned Cloud Resource
        query: mutation.updateCloudResource

  - name: Devices
    description: View, register and remove devices
    usecases:
      - name: List devices
        description: Query one or more registered devices
        query: query.devices
      - name: Register device
        description: Register a new device
        query: mutation.device
      - name: Remove device
        description: Unregister a device
        query: mutation.removeDevice

  - name: Federation
    description: View, create and manage federation guest accounts
    usecases:
      - name: Federation Guests
        description: List all Federation Guest accounts within an org
        query: query.federationGuests
      - name: Federation Guest
        description: Fetch a single Federation Guest account
        query: query.federationGuest
      - name: Edit Federation
        description: Edit a federation
        query: mutation.editFederation
      - name: Create Federation Guest
        description: Create a Federation Guest account
        query: mutation.createFederationGuest
      - name: Edit Federation Guest
        description: Edit an existing Federation Guest account
        query: mutation.editFederationGuest
      - name: Remove Federation Guest
        description: Remove an existing Federation Guest account
        query: mutation.removeFederationGuest

  - name: Management
    description: Endpoints for managing your installation
    usecases:
      - name: API Tokens
        description: Fetch API Tokens
        query: query.apiTokens
      - name: Version
        description: Fetch the version of NearbyOne
        query: query.version

  - name: Okto Resources
    description: View information on Okto Resources
    usecases:
      - name: Okto Resource Logs
        description: View logs for a single Okto Resource
        query: query.oktoResourceLogs

  - name: Provisions
    description:  View, create and manage provisions
    usecases:
      - name: Provisions
        description: List all Provisions in a site
        query: query.provisions
      - name: Provision
        description: Create a provision
        query: mutation.provision

  - name: Services
    description: View information on currently deployed services
    usecases:
      - name: Service chain
        description: Fetch service chain by ID
        query: query.serviceChain
      - name: Service chains
        description: List all service chains
        query: query.serviceChains
      - name: Deploy service chain
        description: Deploy a chain of connected services
        query: mutation.deployServiceChain
      - name: Update service chain
        description: Modify a service chain that is already running
        query: mutation.updateServiceChain
      - name: Rollback service chain
        description: Revert to a previous revision of a service chain
        query: mutation.rollbackServiceChain
      - name: Remove service chain
        description: Undeploy a running service chain
        query: mutation.removeServiceChain
      - name: Okto resource logs
        description: View the logs for a single Okto resource
        query: query.oktoResourceLogs
      - name: Set Block Control
        description: Set a control value on a block connection
        query: mutation.setControlValue

  - name: Settings
    description: Fetch the settings for the currently logged in user
    usecases:
      - name: Settings
        description: Fetch settings
        query: query.settings
      - name: Set default map position
        description: Set the default position and zoom of the map shown in the dashboard
        query: mutation.setDefaultMapPosition
      - name: Set block repo
        description: Set credentials for block chart repo
        query: mutation.setBlockRepo
      - name: Set provision repo
        description: Set credentials for provision chart repo
        query: mutation.setProvisionRepo
      - name: Set template repo
        description: Set credentials for template chart repo
        query: mutation.setTemplateRepo
      - name: Custom Completions
        descriptions: Fetch custom completions for an org
        query: query.customCompletions
      - name: Set Custom Completions
        description: Set custom completions for an org
        query: mutation.setCustomCompletions

  - name: Sites and Organizations
    description: View and update information related to a site/organization
    usecases:
      - name: Organization
        description: Fetch an organization by ID
        query: query.org
      - name: Site
        description: Fetch a site by ID
        query: query.site
      - name: Create site
        description: Create a new site
        query: mutation.createSite
      - name: Edit site
        description: Modify an existing site
        query: mutation.editSite
      - name: Remove site
        description: Remove a site
        query: mutation.removeSite
      - name: Create org
        description: Create a new org
        query: mutation.createOrg
      - name: Edit org
        description: Modify an existing org
        query: mutation.editOrg
      - name: Remove org
        description: Remove an org
        query: mutation.removeOrg

  - name: Users
    description: Manage dashboard user accounts
    usecases:
      - name: Users
        description: List all users
        query: query.users
      - name: Create user
        description: Register a new user
        query: mutation.createUser
      - name: Remove user
        description: Remove a user
        query: mutation.removeUser
      - name: Recruit user
        description: Recruit an existing user to another org
        query: mutation.recruitUser
      - name: Dismiss user
        description: Remove a user from a specific org
        query: mutation.dismissUser
      - name: Generate recovery link
        description: Generate a link for a user to reset their credentials
        query: mutation.generateRecoveryLink
